# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Social Again Live' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Social Again Live
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftyMenu'
  pod 'PKHUD', '~> 5.0'
  pod 'Alamofire', '~> 4.9.1'
  pod 'SDWebImage', '~> 5.0'
  pod 'SideMenu'
  pod 'PWSwitch'
  pod 'SwiftySound'
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'SKCountryPicker'
  pod 'MDatePickerView'
  pod 'ESPullToRefresh'
  pod 'BEMCheckBox'
  pod 'youtube-ios-player-helper-swift'
  pod 'PushNotifications'
  
  target 'WebRTCiOSSDK' do
    # For WebRTCiOSSDK
    pod 'Starscream', '~> 3.1.1'
  end  
  
  # Add Google SDK
  pod 'GoogleSignIn'
  
  # Add FBSDK
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKPlacesKit'
  
  # Add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'

  target 'Social Again LiveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Social Again LiveUITests' do
    # Pods for testing
  end

end
